<?php
// Database Settings (Generated by Setup Wizard)
define('DB_HOST', '127.0.0.1');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_NAME', 'smartschool_db');

// App Root
define('APPROOT', dirname(dirname(__FILE__)) . '/app');

// URL Root (Dynamic detection with Load Balancer SSL offloading support)
$isHttps = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on')
    || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https');
$protocol = $isHttps ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'] ?? 'localhost';
define('URLROOT', $protocol . '://' . $host . '/school');

// Site Name
define('SITENAME', 'Greenwood International School');

// Outgoing email configuration
require_once __DIR__ . '/mail.php';

// =========================================================================
// HIGH-CONCURRENCY & LOAD BALANCING CONFIGURATION (100,000+ USERS)
// =========================================================================
// 1. MySQL Read-Replica Cluster (Read/Write Splitting)
// Comma-separated list of read replica hosts (e.g. '192.168.1.101,192.168.1.102')
// When set, all SELECT queries are load-balanced across replicas, while writes stay on DB_HOST.
if (!defined('DB_READ_HOSTS')) {
    define('DB_READ_HOSTS', getenv('DB_READ_HOSTS') ?: '');
}

// 2. Multi-Server Distributed Session Driver ('file', 'database', or 'redis')
// When running multiple web servers behind a load balancer, set to 'database' or 'redis'
// so users don't get logged out when their request is routed to a different server.
if (!defined('SESSION_DRIVER')) {
    define('SESSION_DRIVER', getenv('SESSION_DRIVER') ?: 'file');
}

// 3. Redis In-Memory Distributed Cache & Session Store
if (!defined('REDIS_HOST')) {
    define('REDIS_HOST', getenv('REDIS_HOST') ?: '127.0.0.1');
}
if (!defined('REDIS_PORT')) {
    define('REDIS_PORT', getenv('REDIS_PORT') ?: 6379);
}
if (!defined('REDIS_PASSWORD')) {
    define('REDIS_PASSWORD', getenv('REDIS_PASSWORD') ?: '');
}

// 4. Trusted Load Balancer & Reverse Proxy CIDRs (AWS ALB, Cloudflare, HAProxy, NGINX)
if (!defined('TRUSTED_PROXIES')) {
    define('TRUSTED_PROXIES', ['127.0.0.1', '::1', '10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']);
}
